server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'nurtech'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
#  datasource:
#    username: 'nurtech'
#    password: 'password'
#    url: jdbc:postgres://localhost:5432/customer
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgresSQLDialect
#        format_sql: 'ture'
#    hibernate:
#      ddl-auto: update
#    show-sql: 'true'

